# Generated by Django 5.1.7 on 2025-09-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10)),
                ('paper_type', models.CharField(choices=[('mid', 'MID'), ('semester', 'SEMESTER'), ('questionbank', 'QUESTIONBANK')], max_length=50)),
                ('question_paper_name', models.CharField(default='newpaper', max_length=100)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.department')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.regulation')),
            ],
        ),
    ]
