# Generated by Django 5.1.6 on 2025-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(choices=[('r-20', 'R-20'), ('r-23', 'R-23')], max_length=100)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'MECH'), ('civil', 'CIVIL')], max_length=100)),
            ],
        ),
    ]
