# Generated by Django 5.1.6 on 2025-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='semister',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('mid', 'MID'), ('semister', 'SEMISTER'), ('questionbank', 'QUESTIONBANK')], default='mid', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'MECH'), ('civil', 'CIVIL')], default='cse', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='regulation',
            field=models.CharField(choices=[('r-20', 'R-20'), ('r-23', 'R-23')], default='r-20', max_length=100),
        ),
    ]
