# Generated by Django 5.1.6 on 2025-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_paper_semister_paper_type_paper_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='files',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
