# Generated by Django 5.1.6 on 2025-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_paper_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='question_paper_name',
            field=models.CharField(default='newpaper', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='files',
            field=models.FileField(default='', upload_to='media/uploads/'),
        ),
    ]
