# Generated by Django 5.1.6 on 2025-03-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_paper_question_paper_name_alter_paper_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='files',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
