# Generated by Django 5.1.6 on 2025-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_paper_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='files',
            field=models.URLField(default=''),
        ),
    ]
