# Generated by Django 5.1.6 on 2025-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_paper_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='files',
        ),
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='temp_uploads/'),
        ),
        migrations.AddField(
            model_name='paper',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
