# Generated by Django 5.1.6 on 2025-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_paper_files_paper_file_paper_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='type',
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('mid', 'MID'), ('semester', 'SEMESTER'), ('questionbank', 'QUESTIONBANK')], default='mid', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
