# Generated by Django 5.1.6 on 2025-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_paper_type_paper_paper_type_alter_paper_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='semister',
            new_name='semester',
        ),
    ]
