# Generated by Django 5.1.6 on 2025-03-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_semister_paper_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
    ]
